Enable adding volume to subject
OpenwaterHealth/SlicerOpenLIFU pull request #116
Opened 2024-10-09 18:15 UTC by sadhana-r

2024-10-15 19:33 UTC, sadhana-r commented
Need to use branch [issue_132](https://github.com/OpenwaterHealth/OpenLIFU-python/tree/issue_132) of openlifu python. Things to review. 
**For adding volume to subject:**
- Add volume to subject button is enabled when a subject is clicked or double clicked.
- Can also right-click a subject and select the option to add volume
- When adding a volume, the filetype filters include volumes and DICOMs. No jsons. 
- Volume name and ID fields autocomplete based on the filepath selected only if empty, but can be edited by the user. Added this feature for convience but noticed in database the volume 'name' is not neccessarily the same as the volume filename. 
- If the volume_id already exists in the database, the user is prompted with a message box. 

**For loading volume from file** 
- The filetype filter includes *.json files. 
- If a json file is selected, the corresponding volume is loaded. The volume name is based on the json metadata. And the metadata id is displayed in the OpenLIFUobjects View. 
- If a volume file is selected and its in the database i.e. has a corresponding json file, then the volume is loaded based on the json metadata. If not in the database, it is loaded using the default Slicer node name and ID.
- I updated session loading to use the json metadata so that all volumes loaded from the database are handled the same way. (This Partly addresses the naming issue in #110).
- I didn't find a [MRMLnode function](https://apidocs.slicer.org/v5.2/classvtkMRMLNode.html) to set the Node ID. Instead, I am including the volume_id as an attribute tag. 
- _Suggestion:_ Now that the volumes in OpenLIFUObjects can have custom volume_ids, I think we need to include a check for duplicate loaded volumes with the same id in the scene. Similar to how there is a check for protocols and transducers. But I wanted to get your thoughts on the other changes first.

2024-10-16 13:53 UTC, sadhana-r commented
@ebrahimebrahim I just updated the openlifu python version and made a small bug fix.

2024-10-16 15:25 UTC, ebrahimebrahim commented
Can you update the PR description to indicate which issues from among #72, #76, #110 should actually be closed by this PR? You can use a [keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like "closes" to make them automatically get closed upon merge.

2024-10-16 19:04 UTC, ebrahimebrahim requested changes
It looks great, really nice work! I am a huge fan of the right click context menu ... need to figure out how those work.

One issue I noticed is that if I choose to overwrite an existing volume but use a volume file with a different filename, then the old volume file is left there dangling. But this is an openlifu issue not a SlicerOpenLIFU issue so I opened https://github.com/OpenwaterHealth/OpenLIFU-python/issues/136.

Remember to rebase to the current main. I think it will be easier if we merge this PR before #117

2024-10-16 19:07 UTC, ebrahimebrahim commented on OpenLIFUData/OpenLIFUData.py
> +from os import path
btw there is is this entire linting tool to automate the process of telling people to use pathlib :laughing: 
https://pypi.org/project/flake8-use-pathlib/
the list of rules may be helpful

2024-10-16 19:19 UTC, sadhana-r commented on OpenLIFUData/Resources/UI/OpenLIFUData.ui
> +         <set>ctkPathLineEdit::Dirs</set>
Seems to be something my QtDesigner does automatically. I'll change it back but what version are you using? I'll try to see if I can prevent this from happening in the future

2024-10-16 19:22 UTC, ebrahimebrahim commented on OpenLIFUData/Resources/UI/OpenLIFUData.ui
> +         <set>ctkPathLineEdit::Dirs</set>
My Qt designer is version 5.12.8 ... maybe I am the one who needs to update IDK
I am on linux with this, not sure if it matters

2024-10-16 22:41 UTC, sadhana-r commented on OpenLIFUData/OpenLIFUData.py
> +                    loadedVolumeNode.SetAttribute('OpenLIFUData.volume_id', volume_id)
I agree, I'll remove the loading of volumes here and it can be loaded as part of the session creation workflow.

2024-10-16 22:52 UTC, sadhana-r commented on OpenLIFUData/OpenLIFUData.py
> +        volume_extensions = ("Volume" + " (*.json *.hdr *.nhdr *.nrrd *.mhd *.mha *.mnc *.nii *.nii.gz *.mgh *.mgz *.mgh.gz *.img *.img.gz *.pic);;" +
I agree. I was trying to figure out how to do that for a while but the extensions are only defined in that C++ file. So I decided to just copy the extensions from there and define a python variable as a workaround for now. Open to a better way of doing this if Sam knows.

2024-10-17 15:38 UTC, sadhana-r commented on OpenLIFULib/OpenLIFULib/__init__.py
> +        volume_node.SetAttribute('OpenLIFUData.volume_id', volume_info['id'])
Created a new issue to handle duplicate volume nodes (#122). Will handle this in a separate PR.

2024-10-17 15:43 UTC, sadhana-r commented on OpenLIFUData/OpenLIFUData.py
> +from os import path
Removed `os.path`. I found it easier than pathlib for handling extensions with multiple dots (i.e. .nii.gz) but using `pathlib` workaround.

2024-10-17 18:41 UTC, ebrahimebrahim approved these changes
TY!!

2024-10-17 18:41 UTC, merged