Add SlicerOpenLIFURun class and implement sonication control module
OpenwaterHealth/SlicerOpenLIFU pull request #125
Opened 2024-11-01 14:23 UTC by sadhana-r

Closes #86 
Closes #87 
- [ ]  Handle overwriting runs with matching IDs
- [ ] Take user input from Save run dialog

2024-11-04 22:28 UTC, ebrahimebrahim requested changes
Clean and easy to read PR, and it works great!

I was initially confused trying to understand how the progress bar update was working, but after some thought I think it makes sense.

Besides the minor comments there are a couple of bigger things that come to mind that weren't in the original plan:

- If the run is aborted, I think we should still save a record that the run happened. When the run is aborted we can force the checkbox to "False" in the dialog because it can be considered not a success. 
- If the run was not successful, maybe we should force the description to be nonempty (this could be enforced at the level of `OnRunCompletedDialog`, so it doesn't let you submit the dialog with an empty description and a failed run).

What do you think?

2024-11-04 22:28 UTC, ebrahimebrahim commented on OpenLIFUData/OpenLIFUData.py
> +                [run_openlifu.id, "Run", run_openlifu.id]
Could include the run `name` in here

2024-11-04 22:28 UTC, ebrahimebrahim commented on OpenLIFUSonicationControl/OpenLIFUSonicationControl.py
> +class onRunCompletedDialog(qt.QDialog):
Class names should us CamelCase starting with a captial so `OnRunCompletedDialog`

2024-11-05 14:22 UTC, sadhana-r commented
> * If the run is aborted, I think we should still save a record that the run happened. When the run is aborted we can force the checkbox to "False" in the dialog because it can be considered not a success.
> * If the run was not successful, maybe we should force the description to be nonempty (this could be enforced at the level of `OnRunCompletedDialog`, so it doesn't let you submit the dialog with an empty description and a failed run).
> 
> What do you think?

I agree, those are good points. I am also wondering, since the run object is only created once a user selects 'Save' in the dialog, do you think we should add a second check inthe case that a user selects 'Cancel' when the dialog pops up. i..e. On cancel, a dialog pops up with "Are you sure you want to discard this run?". Since there is no other way to retrieve the run object if cancelled accidentally.

2024-11-05 14:38 UTC, ebrahimebrahim commented
> since the run object is only created once a user selects 'Save' in the dialog, do you think we should add a second check inthe case that a user selects 'Cancel' when the dialog pops up. i..e. On cancel, a dialog pops up with "Are you sure you want to discard this run?". Since there is no other way to retrieve the run object if cancelled accidentally.

Yes that makes sense. Or we could not even have a cancel button, I think both of those are acceptable ways to do it. I can't think of why someone would insist on not creating/saving  Run at the end.

2024-11-05 19:59 UTC, ebrahimebrahim approved these changes
Code changes look great and the abort and dialog-closing work as expected. TY!

2024-11-05 20:01 UTC, ebrahimebrahim commented
(Don't merge yet of course until the python library update is complete and we do the needed rebase! But we can consider this PR done and move on)

2024-11-07 20:25 UTC, merged